/**
 * A believable two-week history for one household, generated by running real
 * commands through the real core. If the rules change in a way the story no
 * longer fits, this throws (and the test suite catches it).
 *
 * The cast:
 *   Dulmaa  owner. 80 years old; the list is hers.
 *   Anu     her daughter. Can approve.
 *   Bat     her grandson. Can add and tick off directly; may only suggest
 *           changing words or removing things.
 *   Saraa   her carer. May only suggest. Every suggestion so far was accepted.
 *   Bold    a neighbour. Can look.
 */
import {
  addDays,
  createWorkspace,
  dispatch,
  findOpenTask,
  fixedEnv,
  fromAtoms,
  HOUR,
  MINUTE,
  presetPerms,
  preview,
  published,
  startOfDay,
  type Command,
  type Lang,
  type PersonId,
  type TaskId,
  type Workspace,
} from '../core';

const NAMES = {
  en: { dulmaa: 'Dulmaa', anu: 'Anu', bat: 'Bat', saraa: 'Saraa', bold: 'Bold' },
  mn: { dulmaa: 'Дулмаа', anu: 'Ану', bat: 'Бат', saraa: 'Сараа', bold: 'Болд' },
} as const;

const TEXT = {
  pills: { en: 'Take morning pills', mn: 'Өглөөний эм уух' },
  walk: { en: 'Go for a walk', mn: 'Салхинд гарч алхах' },
  bread: { en: 'Buy bread', mn: 'Талх авах' },
  radio: { en: 'Call about the radio', mn: 'Радиогоо засуулахаар залгах' },
  doctor: { en: 'Doctor visit', mn: 'Эмчид үзүүлэх' },
  doctorThu: { en: 'Doctor visit on Thursday at 10:00', mn: 'Пүрэв гарагт 10:00 цагт эмчид үзүүлэх' },
  bill: { en: 'Pay the electricity bill', mn: 'Цахилгааны төлбөр төлөх' },
  bills: { en: 'Pay all the bills', mn: 'Бүх төлбөрөө төлөх' },
  fruit: { en: 'Buy fruit', mn: 'Жимс авах' },
  pressure: { en: 'Check blood pressure', mn: 'Даралтаа үзэх' },
  plants: { en: 'Water the plants', mn: 'Цэцэг услах' },
  soup: { en: 'Cook soup', mn: 'Шөл хийх' },
  tidy: { en: 'Tidy the kitchen', mn: 'Гал тогоо цэвэрлэх' },
  callAnu: { en: 'Call Anu', mn: 'Ануд залгах' },
  kefir: { en: 'Buy kefir', mn: 'Тараг авах' },
} as const;

type TextKey = keyof typeof TEXT;
type Step = readonly [hour: number, minute: number, run: () => void];

export function sampleWorkspace(lang: Lang, now: number): Workspace {
  const today = startOfDay(now);
  const env = fixedEnv(addDays(today, -13) + 8 * HOUR, `s${now.toString(36)}`);
  const name = NAMES[lang];
  const text = (k: TextKey): string => TEXT[k][lang];

  let ws = createWorkspace(env, { name: name.dulmaa, hue: 'clay' });
  const dulmaa = [...ws.replay.state.people.keys()][0] as PersonId;

  const run = (who: PersonId, cmd: Command) => {
    const o = dispatch(ws, who, cmd, env);
    if (o.kind === 'refused') throw new Error(`Sample history: ${cmd.type} was refused (${o.refusal.code})`);
    ws = o.ws;
    return o;
  };
  const id = (k: TextKey): TaskId => {
    const t = findOpenTask(preview(ws), text(k)) ?? findOpenTask(published(ws), text(k));
    if (!t) throw new Error(`Sample history: no open task "${text(k)}"`);
    return t.id;
  };
  const add = (who: PersonId, k: TextKey) => () => void run(who, { type: 'add', text: text(k) });
  const tick = (who: PersonId, k: TextKey) => () => void run(who, { type: 'check', id: id(k), done: true });
  const accept = (who: PersonId) => () => {
    if (!ws.open) throw new Error('Sample history: nothing to accept');
    run(who, { type: 'accept', suggestion: ws.open.id });
  };
  const at = (day: number, h: number, m = 0) => env.set(addDays(today, day) + h * HOUR + m * MINUTE);

  const join = (who: string, perms: ReturnType<typeof presetPerms>, hue: 'sage' | 'sky' | 'plum' | 'ochre') => {
    const o = run(dulmaa, { type: 'addPerson', name: who, perms, hue });
    const c = o.kind === 'published' ? o.version.changes[0] : undefined;
    if (!c || c.op !== 'person.add') throw new Error('Sample history: person not added');
    return c.person.id;
  };

  at(-13, 8, 10);
  const anu = join(name.anu, presetPerms('approver'), 'sage');
  at(-13, 8, 12);
  const bat = join(name.bat, fromAtoms(['do:add', 'do:check', 'suggest:edit', 'suggest:remove']), 'sky');
  at(-13, 8, 14);
  const saraa = join(name.saraa, presetPerms('helper'), 'plum');
  at(-13, 8, 16);
  join(name.bold, presetPerms('viewer'), 'ochre');

  at(-12, 7, 50);
  add(anu, 'radio')();

  const special: Record<number, Step[]> = {
    [-10]: [[9, 30, add(anu, 'doctor')]],
    [-9]: [[12, 0, add(bat, 'bill')]],
    [-8]: [
      [10, 0, add(saraa, 'fruit')],
      [18, 0, accept(dulmaa)],
    ],
    [-7]: [
      [11, 0, tick(saraa, 'fruit')],
      [12, 0, accept(dulmaa)],
    ],
    [-6]: [[14, 0, () => void run(anu, { type: 'edit', id: id('doctor'), text: text('doctorThu') })]],
    [-5]: [
      [9, 40, add(saraa, 'pressure')],
      [10, 30, accept(dulmaa)],
      [10, 45, tick(dulmaa, 'pressure')],
    ],
    [-4]: [
      [
        16,
        0,
        () => {
          // A slip of the finger, taken back straight away.
          const o = run(dulmaa, { type: 'check', id: id('bill'), done: true });
          if (o.kind !== 'published') throw new Error('Sample history: expected a version');
          env.advance(20_000);
          run(dulmaa, { type: 'undo', version: o.version.n });
        },
      ],
    ],
    [-3]: [
      [10, 0, add(saraa, 'plants')],
      [10, 20, accept(dulmaa)],
    ],
    [-2]: [
      [13, 0, () => void run(bat, { type: 'edit', id: id('bill'), text: text('bills') })],
      [
        13,
        30,
        () => {
          if (!ws.open) throw new Error('Sample history: nothing to decline');
          run(dulmaa, { type: 'decline', suggestion: ws.open.id });
        },
      ],
      [15, 0, add(saraa, 'soup')],
      [15, 10, accept(anu)],
      [18, 0, tick(saraa, 'soup')],
      [18, 5, accept(anu)],
    ],
    [-1]: [
      [11, 30, add(saraa, 'tidy')],
      [11, 45, accept(dulmaa)],
      [17, 0, tick(dulmaa, 'tidy')],
      [19, 0, add(dulmaa, 'callAnu')],
    ],
  };

  for (let day = -12; day <= -1; day++) {
    const steps: Step[] = [
      [8, 30, add(dulmaa, 'pills')],
      [9, 5, tick(dulmaa, 'pills')],
    ];
    if (day % 3 === 0) steps.push([10, 15, add(dulmaa, 'walk')], [17, 40, tick(dulmaa, 'walk')]);
    if (Math.abs(day) % 4 === 1) steps.push([11, 0, add(bat, 'bread')], [15, 20, tick(bat, 'bread')]);
    steps.push(...(special[day] ?? []));
    steps.sort((a, b) => a[0] * 60 + a[1] - (b[0] * 60 + b[1]));
    for (const [h, m, step] of steps) {
      at(day, h, m);
      step();
    }
  }

  // Today: spread over the part of the day that has passed, so nothing is in the future.
  const span = Math.max(now - today, 20 * MINUTE);
  const todayAt = (f: number) => env.set(Math.min(now - 1000, today + Math.round(span * f)));
  const todaySteps: Array<readonly [number, () => void]> = [
    [0.3, add(dulmaa, 'pills')],
    [0.34, tick(dulmaa, 'pills')],
    [0.45, add(bat, 'bread')],
    [0.5, add(dulmaa, 'walk')],
    [0.62, tick(bat, 'bread')],
    [0.74, add(saraa, 'kefir')],
    [0.88, () => void run(bat, { type: 'remove', id: id('radio') })],
  ];
  for (const [f, step] of todaySteps) {
    todayAt(f);
    step();
  }

  return ws;
}
