/**
 * Believable two-week histories, generated by running real commands through
 * the real core. If the rules change in a way a story no longer fits, this
 * throws (and the test suite catches it).
 *
 * School (the default): one small school.
 *   Oyunchimeg  director (owner)
 *   Bat-Erdene  manager
 *   Saraa, Tuya teachers
 *   Anu, Khulan, Nomin  students
 *   Dorj        a parent
 *
 * Home: one household.
 *   Dulmaa  owner. 80 years old; the list is hers.
 *   Anu     her daughter. Can approve.
 *   Bat     her grandson. Can add and tick off directly; may only suggest
 *           changing words or removing things.
 *   Saraa   her carer. May only suggest. Every suggestion so far was accepted.
 *   Bold    a neighbour. Can look.
 */
import {
  PLANS,
  peopleWithRole,
  planDraft,
  stepsOf,
  type DraftStep,
  type Hue,
  type Perms,
  type RoleKey,
  type StandardId,
  type StepId,
  addDays,
  createWorkspace,
  dispatch,
  findOpenTask,
  fixedEnv,
  fromAtoms,
  HOUR,
  MINUTE,
  presetPerms,
  preview,
  published,
  startOfDay,
  type Command,
  type Lang,
  type PersonId,
  type TaskId,
  type Workspace,
} from '../core';

const NAMES = {
  en: { dulmaa: 'Dulmaa', anu: 'Anu', bat: 'Bat', saraa: 'Saraa', bold: 'Bold' },
  mn: { dulmaa: 'Дулмаа', anu: 'Ану', bat: 'Бат', saraa: 'Сараа', bold: 'Болд' },
} as const;

const TEXT = {
  pills: { en: 'Take morning pills', mn: 'Өглөөний эм уух' },
  walk: { en: 'Go for a walk', mn: 'Салхинд гарч алхах' },
  bread: { en: 'Buy bread', mn: 'Талх авах' },
  radio: { en: 'Call about the radio', mn: 'Радиогоо засуулахаар залгах' },
  doctor: { en: 'Doctor visit', mn: 'Эмчид үзүүлэх' },
  doctorThu: { en: 'Doctor visit on Thursday at 10:00', mn: 'Пүрэв гарагт 10:00 цагт эмчид үзүүлэх' },
  bill: { en: 'Pay the electricity bill', mn: 'Цахилгааны төлбөр төлөх' },
  bills: { en: 'Pay all the bills', mn: 'Бүх төлбөрөө төлөх' },
  fruit: { en: 'Buy fruit', mn: 'Жимс авах' },
  pressure: { en: 'Check blood pressure', mn: 'Даралтаа үзэх' },
  plants: { en: 'Water the plants', mn: 'Цэцэг услах' },
  soup: { en: 'Cook soup', mn: 'Шөл хийх' },
  tidy: { en: 'Tidy the kitchen', mn: 'Гал тогоо цэвэрлэх' },
  callAnu: { en: 'Call Anu', mn: 'Ануд залгах' },
  kefir: { en: 'Buy kefir', mn: 'Тараг авах' },
} as const;

type TextKey = keyof typeof TEXT;
type Step = readonly [hour: number, minute: number, run: () => void];

export function sampleWorkspace(standard: StandardId, lang: Lang, now: number): Workspace {
  return standard === 'school' ? schoolSample(lang, now) : homeSample(lang, now);
}

function homeSample(lang: Lang, now: number): Workspace {
  const today = startOfDay(now);
  const env = fixedEnv(addDays(today, -13) + 8 * HOUR, `s${now.toString(36)}`);
  const name = NAMES[lang];
  const text = (k: TextKey): string => TEXT[k][lang];

  let ws = createWorkspace(env, { name: name.dulmaa, hue: 'clay' }, 'home');
  const dulmaa = [...ws.replay.state.people.keys()][0] as PersonId;

  const run = (who: PersonId, cmd: Command) => {
    const o = dispatch(ws, who, cmd, env);
    if (o.kind === 'refused') throw new Error(`Sample history: ${cmd.type} was refused (${o.refusal.code})`);
    ws = o.ws;
    return o;
  };
  const id = (k: TextKey): TaskId => {
    const t = findOpenTask(preview(ws), text(k)) ?? findOpenTask(published(ws), text(k));
    if (!t) throw new Error(`Sample history: no open task "${text(k)}"`);
    return t.id;
  };
  const add = (who: PersonId, k: TextKey) => () => void run(who, { type: 'add', text: text(k) });
  const tick = (who: PersonId, k: TextKey) => () => void run(who, { type: 'check', id: id(k), done: true });
  const accept = (who: PersonId) => () => {
    if (!ws.open) throw new Error('Sample history: nothing to accept');
    run(who, { type: 'accept', suggestion: ws.open.id });
  };
  const at = (day: number, h: number, m = 0) => env.set(addDays(today, day) + h * HOUR + m * MINUTE);

  const join = (who: string, perms: ReturnType<typeof presetPerms>, hue: 'sage' | 'sky' | 'plum' | 'ochre') => {
    const o = run(dulmaa, { type: 'addPerson', name: who, perms, hue });
    const c = o.kind === 'published' ? o.version.changes[0] : undefined;
    if (!c || c.op !== 'person.add') throw new Error('Sample history: person not added');
    return c.person.id;
  };

  at(-13, 8, 10);
  const anu = join(name.anu, presetPerms('approver'), 'sage');
  at(-13, 8, 12);
  const bat = join(name.bat, fromAtoms(['do:add', 'do:check', 'suggest:edit', 'suggest:remove']), 'sky');
  at(-13, 8, 14);
  const saraa = join(name.saraa, presetPerms('helper'), 'plum');
  at(-13, 8, 16);
  join(name.bold, presetPerms('viewer'), 'ochre');

  at(-12, 7, 50);
  add(anu, 'radio')();

  const special: Record<number, Step[]> = {
    [-10]: [[9, 30, add(anu, 'doctor')]],
    [-9]: [[12, 0, add(bat, 'bill')]],
    [-8]: [
      [10, 0, add(saraa, 'fruit')],
      [18, 0, accept(dulmaa)],
    ],
    [-7]: [
      [11, 0, tick(saraa, 'fruit')],
      [12, 0, accept(dulmaa)],
    ],
    [-6]: [[14, 0, () => void run(anu, { type: 'edit', id: id('doctor'), text: text('doctorThu') })]],
    [-5]: [
      [9, 40, add(saraa, 'pressure')],
      [10, 30, accept(dulmaa)],
      [10, 45, tick(dulmaa, 'pressure')],
    ],
    [-4]: [
      [
        16,
        0,
        () => {
          // A slip of the finger, taken back straight away.
          const o = run(dulmaa, { type: 'check', id: id('bill'), done: true });
          if (o.kind !== 'published') throw new Error('Sample history: expected a version');
          env.advance(20_000);
          run(dulmaa, { type: 'undo', version: o.version.n });
        },
      ],
    ],
    [-3]: [
      [10, 0, add(saraa, 'plants')],
      [10, 20, accept(dulmaa)],
    ],
    [-2]: [
      [13, 0, () => void run(bat, { type: 'edit', id: id('bill'), text: text('bills') })],
      [
        13,
        30,
        () => {
          if (!ws.open) throw new Error('Sample history: nothing to decline');
          run(dulmaa, { type: 'decline', suggestion: ws.open.id });
        },
      ],
      [15, 0, add(saraa, 'soup')],
      [15, 10, accept(anu)],
      [18, 0, tick(saraa, 'soup')],
      [18, 5, accept(anu)],
    ],
    [-1]: [
      [11, 30, add(saraa, 'tidy')],
      [11, 45, accept(dulmaa)],
      [17, 0, tick(dulmaa, 'tidy')],
      [19, 0, add(dulmaa, 'callAnu')],
    ],
  };

  for (let day = -12; day <= -1; day++) {
    const steps: Step[] = [
      [8, 30, add(dulmaa, 'pills')],
      [9, 5, tick(dulmaa, 'pills')],
    ];
    if (day % 3 === 0) steps.push([10, 15, add(dulmaa, 'walk')], [17, 40, tick(dulmaa, 'walk')]);
    if (Math.abs(day) % 4 === 1) steps.push([11, 0, add(bat, 'bread')], [15, 20, tick(bat, 'bread')]);
    steps.push(...(special[day] ?? []));
    steps.sort((a, b) => a[0] * 60 + a[1] - (b[0] * 60 + b[1]));
    for (const [h, m, step] of steps) {
      at(day, h, m);
      step();
    }
  }

  // Today: spread over the part of the day that has passed, so nothing is in the future.
  const span = Math.max(now - today, 20 * MINUTE);
  const todayAt = (f: number) => env.set(Math.min(now - 1000, today + Math.round(span * f)));
  const todaySteps: Array<readonly [number, () => void]> = [
    [0.3, add(dulmaa, 'pills')],
    [0.34, tick(dulmaa, 'pills')],
    [0.45, add(bat, 'bread')],
    [0.5, add(dulmaa, 'walk')],
    [0.62, tick(bat, 'bread')],
    [0.74, add(saraa, 'kefir')],
    [0.88, () => void run(bat, { type: 'remove', id: id('radio') })],
  ];
  for (const [f, step] of todaySteps) {
    todayAt(f);
    step();
  }

  return ws;
}

/* ------------------------------------------------------------------ school */

const SCHOOL_NAMES = {
  en: {
    director: 'Oyunchimeg',
    manager: 'Bat-Erdene',
    saraa: 'Saraa',
    tuya: 'Tuya',
    anu: 'Anu',
    khulan: 'Khulan',
    nomin: 'Nomin',
    dorj: 'Dorj',
  },
  mn: {
    director: 'Оюунчимэг',
    manager: 'Бат-Эрдэнэ',
    saraa: 'Сараа',
    tuya: 'Туяа',
    anu: 'Ану',
    khulan: 'Хулан',
    nomin: 'Номин',
    dorj: 'Дорж',
  },
} as const;

const SCHOOL_TEXT = {
  fractions: { en: 'Maths homework: fractions', mn: 'Математикийн даалгавар: бутархай' },
  reading: { en: 'Reading homework: chapter 4', mn: 'Уншлагын даалгавар: 4-р бүлэг' },
  give: { en: 'Give the homework', mn: 'Даалгавар өгөх' },
  do: { en: 'Do the homework', mn: 'Даалгавраа хийх' },
  check: { en: 'Check the homework', mn: 'Даалгавар шалгах' },
  artRoom: { en: 'Tidy the art room', mn: 'Зургийн анги цэгцлэх' },
  reportCards: { en: 'Print the report cards', mn: 'Дүнгийн хуудас хэвлэх' },
  museum: { en: 'Field trip to the museum', mn: 'Музей үзэх аялал' },
  plants: { en: 'Bring plants for the classroom', mn: 'Ангид цэцэг авчрах' },
  badges: { en: 'Make name badges', mn: 'Нэрийн тэмдэг хийх' },
  office: { en: 'Call the education office', mn: 'Боловсролын газар руу залгах' },
} as const;

type SchoolKey = keyof typeof SCHOOL_TEXT;

function schoolSample(lang: Lang, now: number): Workspace {
  const today = startOfDay(now);
  const env = fixedEnv(addDays(today, -13) + 8 * HOUR, `k${now.toString(36)}`);
  const name = SCHOOL_NAMES[lang];
  const text = (k: SchoolKey): string => SCHOOL_TEXT[k][lang];

  let ws = createWorkspace(env, { name: name.director, hue: 'clay' }, 'school');
  const director = [...ws.replay.state.people.keys()][0] as PersonId;

  const run = (who: PersonId, cmd: Command) => {
    const o = dispatch(ws, who, cmd, env);
    if (o.kind === 'refused') throw new Error(`School sample: ${cmd.type} was refused (${JSON.stringify(o.refusal)})`);
    ws = o.ws;
    return o;
  };
  const at = (day: number, h: number, m = 0) => env.set(addDays(today, day) + h * HOUR + m * MINUTE);
  const join = (who: string, perms: Perms, hue: Hue) => {
    const o = run(director, { type: 'addPerson', name: who, perms, hue });
    const c = o.kind === 'published' ? o.version.changes[0] : undefined;
    if (!c || c.op !== 'person.add') throw new Error('School sample: person not added');
    return c.person.id;
  };
  const task = (title: string): TaskId => {
    const t = findOpenTask(preview(ws), title) ?? findOpenTask(published(ws), title);
    if (!t) throw new Error(`School sample: no open task "${title}"`);
    return t.id;
  };
  /** The step of a task with these words, given to this person (or the first one with the words). */
  const stepOf = (title: string, words: string, who?: PersonId): StepId => {
    const st = stepsOf(published(ws), task(title)).find((x) => x.text === words && (who === undefined || x.who === who));
    if (!st) throw new Error(`School sample: no step "${words}" in "${title}"`);
    return st.id;
  };
  const tick = (who: PersonId, title: string, words: string, of?: PersonId) =>
    void run(who, { type: 'checkStep', id: stepOf(title, words, of ?? who), done: true });
  const templateText = (plan: string, key: string) => {
    const t = PLANS.find((p) => p.key === plan)?.steps.find((s) => s.key === key);
    if (!t) throw new Error(`School sample: no template step ${plan}/${key}`);
    return t.text[lang];
  };
  const fromTemplate = (who: PersonId, plan: string, title?: string) => {
    const t = PLANS.find((p) => p.key === plan);
    if (!t) throw new Error(`School sample: no plan ${plan}`);
    const steps: DraftStep[] = planDraft(ws, t, lang, who).map(({ key, text: words, who: w, after }) => ({ key, text: words, who: w, after }));
    run(who, { type: 'add', text: title ?? t.title[lang], steps });
  };
  /** A homework plan: the teacher gives it, every student does it at the same time, the teacher checks. */
  const homework = (teacher: PersonId, title: SchoolKey) => {
    const students = peopleWithRole(ws, 'student' as RoleKey);
    const steps: DraftStep[] = [
      { key: 'give', text: text('give'), who: teacher, after: [] },
      ...students.map((s) => ({ key: `do:${s.id}`, text: text('do'), who: s.id, after: ['give'] })),
      { key: 'check', text: text('check'), who: teacher, after: students.map((s) => `do:${s.id}`) },
    ];
    run(teacher, { type: 'add', text: text(title), steps });
  };
  const acceptOpen = (who: PersonId) => {
    if (!ws.open) throw new Error('School sample: nothing to accept');
    run(who, { type: 'accept', suggestion: ws.open.id });
  };

  at(-13, 8, 5);
  const manager = join(name.manager, presetPerms('manager'), 'sage');
  const saraa = join(name.saraa, presetPerms('teacher'), 'sky');
  const tuya = join(name.tuya, presetPerms('teacher'), 'plum');
  const anu = join(name.anu, presetPerms('student'), 'ochre');
  const khulan = join(name.khulan, presetPerms('student'), 'sage');
  const nomin = join(name.nomin, presetPerms('student'), 'sky');
  const dorj = join(name.dorj, presetPerms('parent'), 'ochre');

  const meeting = PLANS.find((p) => p.key === 'parents')!.title[lang];
  const exams = PLANS.find((p) => p.key === 'exam')!.title[lang];

  // Maths homework: given, done by all three students on their own, checked. Long finished.
  at(-12, 9, 0);
  homework(saraa, 'fractions');
  at(-12, 9, 5);
  tick(saraa, text('fractions'), text('give'));
  at(-12, 18, 10);
  tick(anu, text('fractions'), text('do'));
  at(-11, 19, 0);
  tick(khulan, text('fractions'), text('do'));
  at(-11, 20, 30);
  tick(nomin, text('fractions'), text('do'));
  at(-10, 10, 0);
  tick(saraa, text('fractions'), text('check'));

  // The parent meeting, from the ready-made plan. Tuya suggests a step; the manager says OK.
  at(-11, 10, 0);
  fromTemplate(manager, 'parents');
  at(-10, 9, 0);
  tick(manager, meeting, templateText('parents', 'date'));
  at(-10, 11, 0);
  run(tuya, { type: 'addStep', task: task(meeting), text: text('reportCards'), who: tuya });
  at(-10, 11, 30);
  acceptOpen(manager);
  at(-9, 14, 0);
  tick(saraa, meeting, templateText('parents', 'progress'));
  at(-9, 15, 0);
  tick(manager, meeting, templateText('parents', 'hall'));
  at(-8, 10, 0);
  tick(saraa, meeting, templateText('parents', 'invite'));
  at(-8, 16, 0);
  tick(tuya, meeting, text('reportCards'));
  at(-6, 19, 0);
  tick(dorj, meeting, templateText('parents', 'confirm'));

  // Exam week, from the ready-made plan: half done, the papers still to print.
  at(-9, 9, 30);
  fromTemplate(tuya, 'exam');
  at(-8, 9, 0);
  tick(tuya, exams, templateText('exam', 'timetable'));
  at(-7, 10, 0);
  tick(tuya, exams, templateText('exam', 'questions'));
  at(-7, 11, 0);
  tick(manager, exams, templateText('exam', 'rooms'));
  at(-5, 18, 0);
  tick(anu, exams, templateText('exam', 'revise'));
  at(-4, 18, 30);
  tick(khulan, exams, templateText('exam', 'revise'));
  at(-3, 10, 0);
  tick(manager, exams, templateText('exam', 'check'));

  // A student's idea, OK'd by a teacher, and then done by the student.
  at(-7, 12, 0);
  run(anu, { type: 'add', text: text('artRoom') });
  at(-7, 13, 0);
  acceptOpen(saraa);
  at(-6, 15, 0);
  run(anu, { type: 'check', id: task(text('artRoom')), done: true });

  // The director's field trip, from the ready-made plan.
  at(-5, 9, 0);
  fromTemplate(director, 'trip', text('museum'));
  at(-4, 10, 0);
  tick(saraa, text('museum'), templateText('trip', 'place'));
  at(-3, 9, 0);
  tick(director, text('museum'), templateText('trip', 'approve'));
  at(-2, 20, 0);
  tick(dorj, text('museum'), templateText('trip', 'slip'));

  // A student suggests something; it is still waiting.
  at(-2, 12, 0);
  run(khulan, { type: 'add', text: text('plants') });

  // Today: spread over the part of the day that has passed, so nothing is in the future.
  const span = Math.max(now - today, 20 * MINUTE);
  const todayAt = (f: number) => env.set(Math.min(now - 1000, today + Math.round(span * f)));
  todayAt(0.3);
  run(director, { type: 'add', text: text('office') });
  todayAt(0.4);
  homework(saraa, 'reading');
  todayAt(0.45);
  tick(saraa, text('reading'), text('give'));
  todayAt(0.7);
  run(tuya, { type: 'addStep', task: task(text('museum')), text: text('badges'), who: tuya });

  void nomin;
  return ws;
}
